[package]
name = "rx-rust"
version = "0.1.2"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/623637646/rx-rust"
description = "Reactive Programming in Rust inspired by ReactiveX https://reactivex.io/"

[dependencies]
educe = "0.6.0" # Using it to fix the issue: https://github.com/rust-lang/rust/issues/26925  Refer to: https://stackoverflow.com/a/79571732/9315497
slotmap = "1.0.7"
cfg-if = "1.0.1"
futures = { version = "0.3.31", optional = true }
tokio = { version = "1.47.1", optional = true }
async-std = { version = "1.13.1", optional = true }
async-io = { version = "2.4.1", optional = true } # TODO: Use the Timer of it. But it's too heavy.

[dev-dependencies]
pin-project = "1.1.10"
futures = { version = "0.3.31", features = ["thread-pool"] }
tokio = { version = "1.47.1", features = ["full"] }
async-io = { version = "2.4.1" }
rand = "0.9.2"
paste = "1.0.15"

[features]
default = ["multi-threaded"] # default feature.

# no scheduler
multi-threaded = [] # multi-threaded mode without scheduler.
single-threaded = [] # single-threaded mode without scheduler.

# scheduler
local-pool-scheduler = ["single-threaded", "futures", "async-io"] # single-threaded mode with local-pool scheduler
thread-pool-scheduler = ["futures/thread-pool", "async-io"] # multi-threaded mode with thread-pool scheduler
tokio-scheduler = ["futures", "tokio/rt", "tokio/time"] # multi-threaded mode with tokio scheduler
async-std-scheduler = ["futures", "async-std"] # multi-threaded mode with async-std scheduler